### ISSUE TITLE
The installer don't get right if inside a virtual env.

### ISSUE THREAD

**Issue by rockneurotiko** [clione/sikre#5]
I've tried the installer without being inside a virtual env and didn't complain.

Looking into the code, I see that only test if sys.base_prefix exists.

Without virtual env activate:

```
Python 3.4.2 (default, Jan 12 2015, 11:38:40) 
[GCC 4.9.2 20141224 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> hasattr(sys, "base_prefix")
True
>>> sys.base_
sys.base_exec_prefix  sys.base_prefix       
>>> sys.base_prefix
'/usr'
>>> 

```

With virtual env activate:

```
Python 3.4.2 (default, Jan 12 2015, 11:38:40) 
[GCC 4.9.2 20141224 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> hasattr(sys, "base_prefix")
True
>>> sys.base_prefix
'/home/rock/Envs/sikre'
```

Looking I've seen that pyvenv and other virtual env (I've used wirtualenvwrapper) works in different ways.
pyvenv doesn't modify sys.base_prefix and modify sys.prefix.
Other ones create sys.real_prefix with the old base_prefix and modify base_prefix.

I'm gonna do a PR with the changes to test if you are inside a virtual env.

**Comment by oscarcp** [comment]
real_prefix is only returned by virtual environments created with virtualenv, not pyvenv, did you test the installer with pyvenv? (bundled in python 3 virtual env)

**Comment by rockneurotiko** [comment]
The right now installer works with pyvenv, the patch in the PR works with pyvenv and virtualenv.

**Comment by oscarcp** [comment]
Thanks! Merged, I'm closing the issue :)
